### ISSUE TITLE
Tauire platform research

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix-desktop#11]
## service workers
* Tauri does not support service worker https://github.com/tauri-apps/wry/issues/389

**Comment by charlypa** [comment]
Phoenix comprises two parts: an enditor built entirely on web technologies - HTML, CSS, and JS, and a renderer that displays web components natively across Windows, Linux, and Mac. We've currently partitioned these two as individual elements, enhancing our flexibility and minimizing platform-specific code disruptions.

Instead of relying on Rust, we utilize Node as a Tauri sidecar to execute advanced operations. This decision is anchored on Node's superior platform assurances and uniform code execution across all platforms, including Windows, Mac, Linux, and Web.
