### ISSUE TITLE
 Phoenix Code cannot open files in the “HTML source” format.

### ISSUE THREAD

**Issue by godorowski** [phcode-dev/phoenix-desktop#422]
**Describe the bug**

While dragging html file on to editor while having anyother file opened it wont't open dragged file but pops "Phoenix Code cannot open files in the “HTML source” format.", brackets.io didnt had this problem. 

To open other file I have to kill / close Phoenix Code and drag html file on program icon.

**Reproduction**

Open editor with opened any other file/s.
Drag index.html or any other file onto editor window.

**Expected behavior**

It should open this file.

**OS, Browser and Phoenix versions**

    OS: MacOS 14.5 Sonoma
    Version: 3.7.3 (20240525.134214)
    
**Example file that wont open**
    [index.html.zip](https://github.com/phcode-dev/phoenix-desktop/files/15483047/index.html.zip)

**Comment by abose** [comment]
Thanks @godorowski for raising the issue. Drag and drop of files from the OS is not supported currently. This is a limitation of the Tauri framework that we use to create desktop apps. We have been trying to crack this for a while, and raised the issue with Tauri again after this issue was logged. But it appears that it cannot be supported in windows.

See https://discordapp.com/channels/616186924390023171/1245330514404048896 for details.

> The Good news is that For Mac/Linux, we may be able to add drag and drop support soon.

**Comment by abose** [comment]
This is now fixed. Closing. 
Please reopen if its still a problem.
