### ISSUE TITLE
File renaming fails if you only changing the case of letters

### ISSUE THREAD

**Issue by michaljerabek** [phcode-dev/phoenix-desktop#438]
### Describe the bug

File renaming fails if you only changing the case of letters.

### Reproduction

1. Create a file named "a.txt".
2. Rename the file to "A.txt".
3. Error "File already exists." is shown.

### Expected behavior

The file should be renamed.

### OS, Browser and Phoenix versions

Win 11, desktop Phoenix 3.7.3

**Comment by abose** [comment]
Windows file system is case insensitive. So it is expected behavior in windows @michaljerabek . please try this in the system file explorer too, it should fail there.

To adjust case sensitive fs in windows, pleasw follow this link https://learn.microsoft.com/en-us/windows/wsl/case-sensitivity


Closing as this is expected behavior in Windows. Please reopen if files with duplicate case different names can be created from file explorer but not from phcode.

**Comment by michaljerabek** [comment]
Well, you cannot have a.txt and A.txt in the same directory, but you can rename the file to any case you want.

**Comment by abose** [comment]
> Well, you cannot have a.txt and A.txt in the same directory, but you can rename the file to any case you want. (In Brackets it works.)

Ah! I get it now. Thanks for reporting will fix in this release.

**Comment by abose** [comment]
Fixed. closing. will be available in this month's release.
